spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
info:
  app:
    name: "gateway-server"
    description: "Gateway Server"
    version: "1.0.0"